steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - bitbucketevents
      - >-
        --source=https://source.developers.google.com/projects/horvbot/repos/github_dr-horv_horvbot/moveable-aliases/feature-github-integration/paths/src/bitbucketevents/
      - --trigger-http
      - --runtime=nodejs18
      - --region=europe-west1
      - --entry-point=handler
    waitFor:
      - '-'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - slackevents
      - >-
        --source=https://source.developers.google.com/projects/horvbot/repos/github_dr-horv_horvbot/moveable-aliases/feature-github-integration/paths/src/slackevents/
      - --trigger-http
      - --runtime=nodejs18
      - --region=europe-west1
      - --entry-point=handler
    waitFor:
      - '-'
