steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - bitbucketevents
      - --source=src/bitbucketevents
      - --trigger-http

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - slackevents
      - --source=src/slackevents
      - --trigger-http
