steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - bitbucketevents
      - --source=src/bitbucketevents
      - --trigger-http
      - --runtime nodejs10
      - --region europe-west1
      - --entry-point handler
      - --runtime nodejs10
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - slackevents
      - --source=src/slackevents
      - --trigger-http
      - --runtime nodejs10
      - --region europe-west1
      - --entry-point handler
      - --runtime nodejs10
    waitFor: ["-"]
